// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function $$default(param) {
  return React.createElement("div", {
              className: "root"
            }, React.createElement("h1", undefined, "404"), React.createElement("p", undefined, "This page is private or does not exist."), React.createElement("p", undefined, "Go to:", React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement(Link, {
                              href: "/",
                              children: "Home page"
                            })), React.createElement("li", undefined, React.createElement(Link, {
                              href: "/archive",
                              children: "Search"
                            })))));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
